### ISSUE TITLE
libvirtd netcat segfault

### ISSUE THREAD

**Issue by iphands** [clearlinux/clr-boot-manager#243]
**Describe the bug**
Segfault in netcat when connecting to virsh from a remote system.
> Unable to connect to libvirt qemu+ssh://root@hostname.lan/system.

**To Reproduce**
1. Open up virt-manager on remote
2. Try to connect to clear linux host
3. See segfault (faul on clear linux host)

Here is the backtrace from the core dumped on the clearlinux host
```
Core was generated by `nc -U /var/run/libvirt/libvirt-sock'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f2ce568c44a in __strlen_sse2 () from /usr/lib64/libc.so.6
(gdb) bt
#0  0x00007f2ce568c44a in __strlen_sse2 () from /usr/lib64/libc.so.6
#1  0x00007f2ce56799d4 in __GI___strdup (s=0x0) at strdup.c:41
#2  0x000055c7f27cfcd8 in nsock_iod_set_hostname (hostname=0x0, iod=0x55c7f436f270) at ../nsock/src/nsock_iod.c:453
#3  new_iod (mypool=<optimized out>) at ncat_connect.c:907
#4  0x000055c7f27cd535 in ncat_connect () at ncat_connect.c:1018
#5  ncat_connect_mode () at ncat_main.c:1020
#6  main (argc=<optimized out>, argv=<optimized out>) at ncat_main.c:997
```

**Environment (please complete the following information):**
 - Clear Linux OS Version: [swupd info]
```
Distribution:      Clear Linux OS
Installed version: 33840
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update
```

 - clr-boot-manager Version: [clr-boot-manager version]
```
clr-boot-manager - version 3.2.9

Copyright © 2016-2018 Intel Corporation

clr-boot-manager is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or
(at your option) any later version.
```

 - Platform: [hardware infomation]
```
model name	: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
```

** Block Devices:**

 - List of Block Devices: [lsblk -a --json]
```
{
   "blockdevices": [
      {"name":"loop0", "maj:min":"7:0", "rm":false, "size":null, "ro":false, "type":"loop", "mountpoint":null},
      {"name":"loop1", "maj:min":"7:1", "rm":false, "size":null, "ro":false, "type":"loop", "mountpoint":null},
      {"name":"loop2", "maj:min":"7:2", "rm":false, "size":null, "ro":false, "type":"loop", "mountpoint":null},
      {"name":"loop3", "maj:min":"7:3", "rm":false, "size":null, "ro":false, "type":"loop", "mountpoint":null},
      {"name":"loop4", "maj:min":"7:4", "rm":false, "size":null, "ro":false, "type":"loop", "mountpoint":null},
      {"name":"loop5", "maj:min":"7:5", "rm":false, "size":null, "ro":false, "type":"loop", "mountpoint":null},
      {"name":"loop6", "maj:min":"7:6", "rm":false, "size":null, "ro":false, "type":"loop", "mountpoint":null},
      {"name":"loop7", "maj:min":"7:7", "rm":false, "size":null, "ro":false, "type":"loop", "mountpoint":null},
      {"name":"sda", "maj:min":"8:0", "rm":false, "size":"1.8T", "ro":false, "type":"disk", "mountpoint":null,
         "children": [
            {"name":"sda1", "maj:min":"8:1", "rm":false, "size":"142M", "ro":false, "type":"part", "mountpoint":null},
            {"name":"sda2", "maj:min":"8:2", "rm":false, "size":"244M", "ro":false, "type":"part", "mountpoint":"[SWAP]"},
            {"name":"sda3", "maj:min":"8:3", "rm":false, "size":"1.8T", "ro":false, "type":"part", "mountpoint":"/"}
         ]
      },
      {"name":"sdb", "maj:min":"8:16", "rm":false, "size":"3.6T", "ro":false, "type":"disk", "mountpoint":"/main"},
      {"name":"sdc", "maj:min":"8:32", "rm":false, "size":"3.6T", "ro":false, "type":"disk", "mountpoint":null},
      {"name":"sdd", "maj:min":"8:48", "rm":false, "size":"3.6T", "ro":false, "type":"disk", "mountpoint":null},
      {"name":"sde", "maj:min":"8:64", "rm":false, "size":"3.6T", "ro":false, "type":"disk", "mountpoint":null},
      {"name":"sdf", "maj:min":"8:80", "rm":false, "size":"3.6T", "ro":false, "type":"disk", "mountpoint":null}
   ]
}
```

**Additional context**

**Comment by iphands** [comment]
Shoot :( this is the wrong repo I think... is clearlinux/distribution the proper place?

**Comment by iphands** [comment]
Closing.... looks like its already open here:
https://github.com/clearlinux/distribution/issues/2152
